image: node:latest 

# stages: 
#  - lint
#  - test
#  - deploy

# lint: 
#   stage: lint
#   script: 
#     - npm install 
#     - npx eslint ./ 

# test:
#   stage: test
#   script:
#     - npm install
#     - npm test

deploy: 
  stage: deploy 
  script: 
    - ssh -tt 40231676@hpdc.eeecs.qub.ac.uk
    - expect "40231676@hpdc.eeecs.qub.ac.uk's password:"
    - send "testpassword"