image: node:latest 

stages: 
#  - lint
#  - test
 - deploy

# lint: 
#   stage: lint
#   tags: ecg-runner-server
#   script: 
#     - npm install 
#     - npx eslint ./ 

# test:
#   stage: test
#   tags: ecg-runner-server
#   script:
#     - npm install
#     - npm test

deploy: 
  stage: deploy
  tags: 
   - ecg-runner-server
  before_script:
   - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
   - eval $(ssh-agent -s)
   - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh
   - ssh-keyscan $SERVER_IPADDRESS >> ~/.ssh/known_hosts
   - chmod 644 ~/.ssh/known_hosts
  script:
   - ssh $SSH_USER@$SERVER_IPADDRESS "hostname && echo 'Welcome!!!' > welcome.txt"
   - pwd